# Site settings
title: "Muhammad Usama - Resume"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Muhammad Usama"
resume_title:                   "Senior Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "usama28232@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+92-341-313-8998"
resume_contact_address:         "R-1244 Block 14, F.B Area - Dastagir Karachi Pakistan"

resume_header_contact_info:     "Karachi • +92-341-313-8998"
display_header_contact_info:    "true"

resume_header_intro: "<p>I am currently employed in Contour Software (A Subsidiary of Constellation Software Inc.) working remotely in Cayenta (Canada) on GO, Java Spring Boot, Hibernate, Spring Security with Angular and Thymeleaf for front-end framework and template engine respectively. I have 7+ years of working experience; I have also worked as a freelancer since 2015 on a number of technologies on Fiverr.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/usama28232"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/usama28232"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
